// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.wbq.protobuf.proto;

public final class Auth {
	private Auth() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface CRegisterOrBuilder extends
			// @@protoc_insertion_point(interface_extends:CRegister)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string userid = 1;</code>
		 */
		String getUserid();

		/**
		 * <code>string userid = 1;</code>
		 */
		com.google.protobuf.ByteString
		getUseridBytes();

		/**
		 * <code>string passwd = 2;</code>
		 */
		String getPasswd();

		/**
		 * <code>string passwd = 2;</code>
		 */
		com.google.protobuf.ByteString
		getPasswdBytes();
	}

	/**
	 * Protobuf type {@code CRegister}
	 */
	public static final class CRegister extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:CRegister)
			CRegisterOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use CRegister.newBuilder() to construct.
		private CRegister(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private CRegister() {
			userid_ = "";
			passwd_ = "";
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private CRegister(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							String s = input.readStringRequireUtf8();

							userid_ = s;
							break;
						}
						case 18: {
							String s = input.readStringRequireUtf8();

							passwd_ = s;
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return Auth.internal_static_CRegister_descriptor;
		}

		@Override
		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return Auth.internal_static_CRegister_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							Auth.CRegister.class, Auth.CRegister.Builder.class);
		}

		public static final int USERID_FIELD_NUMBER = 1;

		private volatile Object userid_;

		/**
		 * <code>string userid = 1;</code>
		 */
		public String getUserid() {
			Object ref = userid_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				userid_ = s;
				return s;
			}
		}

		/**
		 * <code>string userid = 1;</code>
		 */
		public com.google.protobuf.ByteString
		getUseridBytes() {
			Object ref = userid_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				userid_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PASSWD_FIELD_NUMBER = 2;

		private volatile Object passwd_;

		/**
		 * <code>string passwd = 2;</code>
		 */
		public String getPasswd() {
			Object ref = passwd_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				passwd_ = s;
				return s;
			}
		}

		/**
		 * <code>string passwd = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getPasswdBytes() {
			Object ref = passwd_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				passwd_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (!getUseridBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userid_);
			}
			if (!getPasswdBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, passwd_);
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (!getUseridBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userid_);
			}
			if (!getPasswdBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, passwd_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Auth.CRegister)) {
				return super.equals(obj);
			}
			Auth.CRegister other = (Auth.CRegister) obj;

			boolean result = true;
			result = result && getUserid()
					.equals(other.getUserid());
			result = result && getPasswd()
					.equals(other.getPasswd());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + USERID_FIELD_NUMBER;
			hash = (53 * hash) + getUserid().hashCode();
			hash = (37 * hash) + PASSWD_FIELD_NUMBER;
			hash = (53 * hash) + getPasswd().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Auth.CRegister parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.CRegister parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.CRegister parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.CRegister parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.CRegister parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.CRegister parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.CRegister parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Auth.CRegister parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Auth.CRegister parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static Auth.CRegister parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Auth.CRegister parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Auth.CRegister parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Auth.CRegister prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code CRegister}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:CRegister)
				Auth.CRegisterOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return Auth.internal_static_CRegister_descriptor;
			}

			@Override
			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return Auth.internal_static_CRegister_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Auth.CRegister.class, Auth.CRegister.Builder.class);
			}

			// Construct using com.wbq.protobuf.proto.Auth.CRegister.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				userid_ = "";

				passwd_ = "";

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return Auth.internal_static_CRegister_descriptor;
			}

			@Override
			public Auth.CRegister getDefaultInstanceForType() {
				return Auth.CRegister.getDefaultInstance();
			}

			@Override
			public Auth.CRegister build() {
				Auth.CRegister result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public Auth.CRegister buildPartial() {
				Auth.CRegister result = new Auth.CRegister(this);
				result.userid_ = userid_;
				result.passwd_ = passwd_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Auth.CRegister) {
					return mergeFrom((Auth.CRegister) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Auth.CRegister other) {
				if (other == Auth.CRegister.getDefaultInstance()) return this;
				if (!other.getUserid().isEmpty()) {
					userid_ = other.userid_;
					onChanged();
				}
				if (!other.getPasswd().isEmpty()) {
					passwd_ = other.passwd_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Auth.CRegister parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Auth.CRegister) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private Object userid_ = "";

			/**
			 * <code>string userid = 1;</code>
			 */
			public String getUserid() {
				Object ref = userid_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					userid_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <code>string userid = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getUseridBytes() {
				Object ref = userid_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					userid_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string userid = 1;</code>
			 */
			public Builder setUserid(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				userid_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string userid = 1;</code>
			 */
			public Builder clearUserid() {

				userid_ = getDefaultInstance().getUserid();
				onChanged();
				return this;
			}

			/**
			 * <code>string userid = 1;</code>
			 */
			public Builder setUseridBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				userid_ = value;
				onChanged();
				return this;
			}

			private Object passwd_ = "";

			/**
			 * <code>string passwd = 2;</code>
			 */
			public String getPasswd() {
				Object ref = passwd_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					passwd_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <code>string passwd = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getPasswdBytes() {
				Object ref = passwd_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					passwd_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string passwd = 2;</code>
			 */
			public Builder setPasswd(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				passwd_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string passwd = 2;</code>
			 */
			public Builder clearPasswd() {

				passwd_ = getDefaultInstance().getPasswd();
				onChanged();
				return this;
			}

			/**
			 * <code>string passwd = 2;</code>
			 */
			public Builder setPasswdBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				passwd_ = value;
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:CRegister)
		}

		// @@protoc_insertion_point(class_scope:CRegister)
		private static final Auth.CRegister DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Auth.CRegister();
		}

		public static Auth.CRegister getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<CRegister>
				PARSER = new com.google.protobuf.AbstractParser<CRegister>() {
			@Override
			public CRegister parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CRegister(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<CRegister> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<CRegister> getParserForType() {
			return PARSER;
		}

		@Override
		public Auth.CRegister getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface CLoginOrBuilder extends
			// @@protoc_insertion_point(interface_extends:CLogin)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 * 用户账户id
		 * </pre>
		 *
		 * <code>string userid = 1;</code>
		 */
		String getUserid();

		/**
		 * <pre>
		 * 用户账户id
		 * </pre>
		 *
		 * <code>string userid = 1;</code>
		 */
		com.google.protobuf.ByteString
		getUseridBytes();

		/**
		 * <pre>
		 * 用户密码
		 * </pre>
		 *
		 * <code>string passwd = 2;</code>
		 */
		String getPasswd();

		/**
		 * <pre>
		 * 用户密码
		 * </pre>
		 *
		 * <code>string passwd = 2;</code>
		 */
		com.google.protobuf.ByteString
		getPasswdBytes();

		/**
		 * <pre>
		 * 客户端平台:android,ios,web
		 * </pre>
		 *
		 * <code>string platform = 3;</code>
		 */
		String getPlatform();

		/**
		 * <pre>
		 * 客户端平台:android,ios,web
		 * </pre>
		 *
		 * <code>string platform = 3;</code>
		 */
		com.google.protobuf.ByteString
		getPlatformBytes();

		/**
		 * <pre>
		 * APP版本号
		 * </pre>
		 *
		 * <code>string app_version = 4;</code>
		 */
		String getAppVersion();

		/**
		 * <pre>
		 * APP版本号
		 * </pre>
		 *
		 * <code>string app_version = 4;</code>
		 */
		com.google.protobuf.ByteString
		getAppVersionBytes();
	}

	/**
	 * Protobuf type {@code CLogin}
	 */
	public static final class CLogin extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:CLogin)
			CLoginOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use CLogin.newBuilder() to construct.
		private CLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private CLogin() {
			userid_ = "";
			passwd_ = "";
			platform_ = "";
			appVersion_ = "";
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private CLogin(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							String s = input.readStringRequireUtf8();

							userid_ = s;
							break;
						}
						case 18: {
							String s = input.readStringRequireUtf8();

							passwd_ = s;
							break;
						}
						case 26: {
							String s = input.readStringRequireUtf8();

							platform_ = s;
							break;
						}
						case 34: {
							String s = input.readStringRequireUtf8();

							appVersion_ = s;
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return Auth.internal_static_CLogin_descriptor;
		}

		@Override
		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return Auth.internal_static_CLogin_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							Auth.CLogin.class, Auth.CLogin.Builder.class);
		}

		public static final int USERID_FIELD_NUMBER = 1;

		private volatile Object userid_;

		/**
		 * <pre>
		 * 用户账户id
		 * </pre>
		 *
		 * <code>string userid = 1;</code>
		 */
		public String getUserid() {
			Object ref = userid_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				userid_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * 用户账户id
		 * </pre>
		 *
		 * <code>string userid = 1;</code>
		 */
		public com.google.protobuf.ByteString
		getUseridBytes() {
			Object ref = userid_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				userid_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PASSWD_FIELD_NUMBER = 2;

		private volatile Object passwd_;

		/**
		 * <pre>
		 * 用户密码
		 * </pre>
		 *
		 * <code>string passwd = 2;</code>
		 */
		public String getPasswd() {
			Object ref = passwd_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				passwd_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * 用户密码
		 * </pre>
		 *
		 * <code>string passwd = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getPasswdBytes() {
			Object ref = passwd_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				passwd_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PLATFORM_FIELD_NUMBER = 3;

		private volatile Object platform_;

		/**
		 * <pre>
		 * 客户端平台:android,ios,web
		 * </pre>
		 *
		 * <code>string platform = 3;</code>
		 */
		public String getPlatform() {
			Object ref = platform_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				platform_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * 客户端平台:android,ios,web
		 * </pre>
		 *
		 * <code>string platform = 3;</code>
		 */
		public com.google.protobuf.ByteString
		getPlatformBytes() {
			Object ref = platform_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				platform_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int APP_VERSION_FIELD_NUMBER = 4;

		private volatile Object appVersion_;

		/**
		 * <pre>
		 * APP版本号
		 * </pre>
		 *
		 * <code>string app_version = 4;</code>
		 */
		public String getAppVersion() {
			Object ref = appVersion_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				appVersion_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * APP版本号
		 * </pre>
		 *
		 * <code>string app_version = 4;</code>
		 */
		public com.google.protobuf.ByteString
		getAppVersionBytes() {
			Object ref = appVersion_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				appVersion_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (!getUseridBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userid_);
			}
			if (!getPasswdBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, passwd_);
			}
			if (!getPlatformBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, platform_);
			}
			if (!getAppVersionBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appVersion_);
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (!getUseridBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userid_);
			}
			if (!getPasswdBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, passwd_);
			}
			if (!getPlatformBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, platform_);
			}
			if (!getAppVersionBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appVersion_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Auth.CLogin)) {
				return super.equals(obj);
			}
			Auth.CLogin other = (Auth.CLogin) obj;

			boolean result = true;
			result = result && getUserid()
					.equals(other.getUserid());
			result = result && getPasswd()
					.equals(other.getPasswd());
			result = result && getPlatform()
					.equals(other.getPlatform());
			result = result && getAppVersion()
					.equals(other.getAppVersion());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + USERID_FIELD_NUMBER;
			hash = (53 * hash) + getUserid().hashCode();
			hash = (37 * hash) + PASSWD_FIELD_NUMBER;
			hash = (53 * hash) + getPasswd().hashCode();
			hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
			hash = (53 * hash) + getPlatform().hashCode();
			hash = (37 * hash) + APP_VERSION_FIELD_NUMBER;
			hash = (53 * hash) + getAppVersion().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Auth.CLogin parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.CLogin parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.CLogin parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.CLogin parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.CLogin parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.CLogin parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.CLogin parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Auth.CLogin parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Auth.CLogin parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static Auth.CLogin parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Auth.CLogin parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Auth.CLogin parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Auth.CLogin prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code CLogin}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:CLogin)
				Auth.CLoginOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return Auth.internal_static_CLogin_descriptor;
			}

			@Override
			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return Auth.internal_static_CLogin_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Auth.CLogin.class, Auth.CLogin.Builder.class);
			}

			// Construct using com.wbq.protobuf.proto.Auth.CLogin.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				userid_ = "";

				passwd_ = "";

				platform_ = "";

				appVersion_ = "";

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return Auth.internal_static_CLogin_descriptor;
			}

			@Override
			public Auth.CLogin getDefaultInstanceForType() {
				return Auth.CLogin.getDefaultInstance();
			}

			@Override
			public Auth.CLogin build() {
				Auth.CLogin result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public Auth.CLogin buildPartial() {
				Auth.CLogin result = new Auth.CLogin(this);
				result.userid_ = userid_;
				result.passwd_ = passwd_;
				result.platform_ = platform_;
				result.appVersion_ = appVersion_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Auth.CLogin) {
					return mergeFrom((Auth.CLogin) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Auth.CLogin other) {
				if (other == Auth.CLogin.getDefaultInstance()) return this;
				if (!other.getUserid().isEmpty()) {
					userid_ = other.userid_;
					onChanged();
				}
				if (!other.getPasswd().isEmpty()) {
					passwd_ = other.passwd_;
					onChanged();
				}
				if (!other.getPlatform().isEmpty()) {
					platform_ = other.platform_;
					onChanged();
				}
				if (!other.getAppVersion().isEmpty()) {
					appVersion_ = other.appVersion_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Auth.CLogin parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Auth.CLogin) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private Object userid_ = "";

			/**
			 * <pre>
			 * 用户账户id
			 * </pre>
			 *
			 * <code>string userid = 1;</code>
			 */
			public String getUserid() {
				Object ref = userid_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					userid_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 * 用户账户id
			 * </pre>
			 *
			 * <code>string userid = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getUseridBytes() {
				Object ref = userid_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					userid_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * 用户账户id
			 * </pre>
			 *
			 * <code>string userid = 1;</code>
			 */
			public Builder setUserid(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				userid_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 用户账户id
			 * </pre>
			 *
			 * <code>string userid = 1;</code>
			 */
			public Builder clearUserid() {

				userid_ = getDefaultInstance().getUserid();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 用户账户id
			 * </pre>
			 *
			 * <code>string userid = 1;</code>
			 */
			public Builder setUseridBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				userid_ = value;
				onChanged();
				return this;
			}

			private Object passwd_ = "";

			/**
			 * <pre>
			 * 用户密码
			 * </pre>
			 *
			 * <code>string passwd = 2;</code>
			 */
			public String getPasswd() {
				Object ref = passwd_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					passwd_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 * 用户密码
			 * </pre>
			 *
			 * <code>string passwd = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getPasswdBytes() {
				Object ref = passwd_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					passwd_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * 用户密码
			 * </pre>
			 *
			 * <code>string passwd = 2;</code>
			 */
			public Builder setPasswd(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				passwd_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 用户密码
			 * </pre>
			 *
			 * <code>string passwd = 2;</code>
			 */
			public Builder clearPasswd() {

				passwd_ = getDefaultInstance().getPasswd();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 用户密码
			 * </pre>
			 *
			 * <code>string passwd = 2;</code>
			 */
			public Builder setPasswdBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				passwd_ = value;
				onChanged();
				return this;
			}

			private Object platform_ = "";

			/**
			 * <pre>
			 * 客户端平台:android,ios,web
			 * </pre>
			 *
			 * <code>string platform = 3;</code>
			 */
			public String getPlatform() {
				Object ref = platform_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					platform_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 * 客户端平台:android,ios,web
			 * </pre>
			 *
			 * <code>string platform = 3;</code>
			 */
			public com.google.protobuf.ByteString
			getPlatformBytes() {
				Object ref = platform_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					platform_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * 客户端平台:android,ios,web
			 * </pre>
			 *
			 * <code>string platform = 3;</code>
			 */
			public Builder setPlatform(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				platform_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 客户端平台:android,ios,web
			 * </pre>
			 *
			 * <code>string platform = 3;</code>
			 */
			public Builder clearPlatform() {

				platform_ = getDefaultInstance().getPlatform();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 客户端平台:android,ios,web
			 * </pre>
			 *
			 * <code>string platform = 3;</code>
			 */
			public Builder setPlatformBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				platform_ = value;
				onChanged();
				return this;
			}

			private Object appVersion_ = "";

			/**
			 * <pre>
			 * APP版本号
			 * </pre>
			 *
			 * <code>string app_version = 4;</code>
			 */
			public String getAppVersion() {
				Object ref = appVersion_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					appVersion_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 * APP版本号
			 * </pre>
			 *
			 * <code>string app_version = 4;</code>
			 */
			public com.google.protobuf.ByteString
			getAppVersionBytes() {
				Object ref = appVersion_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					appVersion_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * APP版本号
			 * </pre>
			 *
			 * <code>string app_version = 4;</code>
			 */
			public Builder setAppVersion(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				appVersion_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * APP版本号
			 * </pre>
			 *
			 * <code>string app_version = 4;</code>
			 */
			public Builder clearAppVersion() {

				appVersion_ = getDefaultInstance().getAppVersion();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * APP版本号
			 * </pre>
			 *
			 * <code>string app_version = 4;</code>
			 */
			public Builder setAppVersionBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				appVersion_ = value;
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:CLogin)
		}

		// @@protoc_insertion_point(class_scope:CLogin)
		private static final Auth.CLogin DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Auth.CLogin();
		}

		public static Auth.CLogin getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<CLogin>
				PARSER = new com.google.protobuf.AbstractParser<CLogin>() {
			@Override
			public CLogin parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CLogin(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<CLogin> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<CLogin> getParserForType() {
			return PARSER;
		}

		@Override
		public Auth.CLogin getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface SResponseOrBuilder extends
			// @@protoc_insertion_point(interface_extends:SResponse)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 *返回码
		 * </pre>
		 *
		 * <code>int32 code = 1;</code>
		 */
		int getCode();

		/**
		 * <pre>
		 *描述
		 * </pre>
		 *
		 * <code>string desc = 2;</code>
		 */
		String getDesc();

		/**
		 * <pre>
		 *描述
		 * </pre>
		 *
		 * <code>string desc = 2;</code>
		 */
		com.google.protobuf.ByteString
		getDescBytes();
	}

	/**
	 * <pre>
	 *code：
	 *200 -- ok
	 *404 -- error
	 *300 -- dumplicated registery
	 * </pre>
	 *
	 * Protobuf type {@code SResponse}
	 */
	public static final class SResponse extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:SResponse)
			SResponseOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use SResponse.newBuilder() to construct.
		private SResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private SResponse() {
			code_ = 0;
			desc_ = "";
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private SResponse(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {

							code_ = input.readInt32();
							break;
						}
						case 18: {
							String s = input.readStringRequireUtf8();

							desc_ = s;
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return Auth.internal_static_SResponse_descriptor;
		}

		@Override
		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return Auth.internal_static_SResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							Auth.SResponse.class, Auth.SResponse.Builder.class);
		}

		public static final int CODE_FIELD_NUMBER = 1;

		private int code_;

		/**
		 * <pre>
		 *返回码
		 * </pre>
		 *
		 * <code>int32 code = 1;</code>
		 */
		public int getCode() {
			return code_;
		}

		public static final int DESC_FIELD_NUMBER = 2;

		private volatile Object desc_;

		/**
		 * <pre>
		 *描述
		 * </pre>
		 *
		 * <code>string desc = 2;</code>
		 */
		public String getDesc() {
			Object ref = desc_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				desc_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 *描述
		 * </pre>
		 *
		 * <code>string desc = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getDescBytes() {
			Object ref = desc_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				desc_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (code_ != 0) {
				output.writeInt32(1, code_);
			}
			if (!getDescBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (code_ != 0) {
				size += com.google.protobuf.CodedOutputStream
						.computeInt32Size(1, code_);
			}
			if (!getDescBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Auth.SResponse)) {
				return super.equals(obj);
			}
			Auth.SResponse other = (Auth.SResponse) obj;

			boolean result = true;
			result = result && (getCode()
					== other.getCode());
			result = result && getDesc()
					.equals(other.getDesc());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + CODE_FIELD_NUMBER;
			hash = (53 * hash) + getCode();
			hash = (37 * hash) + DESC_FIELD_NUMBER;
			hash = (53 * hash) + getDesc().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Auth.SResponse parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.SResponse parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.SResponse parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.SResponse parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.SResponse parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Auth.SResponse parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Auth.SResponse parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Auth.SResponse parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Auth.SResponse parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static Auth.SResponse parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Auth.SResponse parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Auth.SResponse parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Auth.SResponse prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * <pre>
		 *code：
		 *200 -- ok
		 *404 -- error
		 *300 -- dumplicated registery
		 * </pre>
		 *
		 * Protobuf type {@code SResponse}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:SResponse)
				Auth.SResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return Auth.internal_static_SResponse_descriptor;
			}

			@Override
			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return Auth.internal_static_SResponse_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Auth.SResponse.class, Auth.SResponse.Builder.class);
			}

			// Construct using com.wbq.protobuf.proto.Auth.SResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				code_ = 0;

				desc_ = "";

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return Auth.internal_static_SResponse_descriptor;
			}

			@Override
			public Auth.SResponse getDefaultInstanceForType() {
				return Auth.SResponse.getDefaultInstance();
			}

			@Override
			public Auth.SResponse build() {
				Auth.SResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public Auth.SResponse buildPartial() {
				Auth.SResponse result = new Auth.SResponse(this);
				result.code_ = code_;
				result.desc_ = desc_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Auth.SResponse) {
					return mergeFrom((Auth.SResponse) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Auth.SResponse other) {
				if (other == Auth.SResponse.getDefaultInstance()) return this;
				if (other.getCode() != 0) {
					setCode(other.getCode());
				}
				if (!other.getDesc().isEmpty()) {
					desc_ = other.desc_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Auth.SResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Auth.SResponse) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int code_;

			/**
			 * <pre>
			 *返回码
			 * </pre>
			 *
			 * <code>int32 code = 1;</code>
			 */
			public int getCode() {
				return code_;
			}

			/**
			 * <pre>
			 *返回码
			 * </pre>
			 *
			 * <code>int32 code = 1;</code>
			 */
			public Builder setCode(int value) {

				code_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *返回码
			 * </pre>
			 *
			 * <code>int32 code = 1;</code>
			 */
			public Builder clearCode() {

				code_ = 0;
				onChanged();
				return this;
			}

			private Object desc_ = "";

			/**
			 * <pre>
			 *描述
			 * </pre>
			 *
			 * <code>string desc = 2;</code>
			 */
			public String getDesc() {
				Object ref = desc_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					desc_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 *描述
			 * </pre>
			 *
			 * <code>string desc = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getDescBytes() {
				Object ref = desc_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					desc_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 *描述
			 * </pre>
			 *
			 * <code>string desc = 2;</code>
			 */
			public Builder setDesc(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				desc_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *描述
			 * </pre>
			 *
			 * <code>string desc = 2;</code>
			 */
			public Builder clearDesc() {

				desc_ = getDefaultInstance().getDesc();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *描述
			 * </pre>
			 *
			 * <code>string desc = 2;</code>
			 */
			public Builder setDescBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				desc_ = value;
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:SResponse)
		}

		// @@protoc_insertion_point(class_scope:SResponse)
		private static final Auth.SResponse DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Auth.SResponse();
		}

		public static Auth.SResponse getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<SResponse>
				PARSER = new com.google.protobuf.AbstractParser<SResponse>() {
			@Override
			public SResponse parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new SResponse(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<SResponse> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<SResponse> getParserForType() {
			return PARSER;
		}

		@Override
		public Auth.SResponse getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_CRegister_descriptor;

	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_CRegister_fieldAccessorTable;

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_CLogin_descriptor;

	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_CLogin_fieldAccessorTable;

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_SResponse_descriptor;

	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_SResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		String[] descriptorData = {
				"\n\013login.proto\"+\n\tCRegister\022\016\n\006userid\030\001 \001" +
						"(\t\022\016\n\006passwd\030\002 \001(\t\"O\n\006CLogin\022\016\n\006userid\030\001" +
						" \001(\t\022\016\n\006passwd\030\002 \001(\t\022\020\n\010platform\030\003 \001(\t\022\023" +
						"\n\013app_version\030\004 \001(\t\"\'\n\tSResponse\022\014\n\004code" +
						"\030\001 \001(\005\022\014\n\004desc\030\002 \001(\tB\036\n\026com.wbq.protobuf" +
						".protoB\004Authb\006proto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {
						}, assigner);
		internal_static_CRegister_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_CRegister_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_CRegister_descriptor,
				new String[] {"Userid", "Passwd",});
		internal_static_CLogin_descriptor =
				getDescriptor().getMessageTypes().get(1);
		internal_static_CLogin_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_CLogin_descriptor,
				new String[] {"Userid", "Passwd", "Platform", "AppVersion",});
		internal_static_SResponse_descriptor =
				getDescriptor().getMessageTypes().get(2);
		internal_static_SResponse_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_SResponse_descriptor,
				new String[] {"Code", "Desc",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
