// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.wbq.protobuf.proto;

public final class Chat {
	private Chat() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface CPrivateChatOrBuilder extends
			// @@protoc_insertion_point(interface_extends:CPrivateChat)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 *发送消息者的userid
		 * </pre>
		 *
		 * <code>string self = 1;</code>
		 */
		String getSelf();

		/**
		 * <pre>
		 *发送消息者的userid
		 * </pre>
		 *
		 * <code>string self = 1;</code>
		 */
		com.google.protobuf.ByteString
		getSelfBytes();

		/**
		 * <pre>
		 *消息目标的userid
		 * </pre>
		 *
		 * <code>string dest = 2;</code>
		 */
		String getDest();

		/**
		 * <pre>
		 *消息目标的userid
		 * </pre>
		 *
		 * <code>string dest = 2;</code>
		 */
		com.google.protobuf.ByteString
		getDestBytes();

		/**
		 * <pre>
		 *消息内容
		 * </pre>
		 *
		 * <code>string content = 3;</code>
		 */
		String getContent();

		/**
		 * <pre>
		 *消息内容
		 * </pre>
		 *
		 * <code>string content = 3;</code>
		 */
		com.google.protobuf.ByteString
		getContentBytes();
	}

	/**
	 * Protobuf type {@code CPrivateChat}
	 */
	public static final class CPrivateChat extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:CPrivateChat)
			CPrivateChatOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use CPrivateChat.newBuilder() to construct.
		private CPrivateChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private CPrivateChat() {
			self_ = "";
			dest_ = "";
			content_ = "";
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private CPrivateChat(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							String s = input.readStringRequireUtf8();

							self_ = s;
							break;
						}
						case 18: {
							String s = input.readStringRequireUtf8();

							dest_ = s;
							break;
						}
						case 26: {
							String s = input.readStringRequireUtf8();

							content_ = s;
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return Chat.internal_static_CPrivateChat_descriptor;
		}

		@Override
		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return Chat.internal_static_CPrivateChat_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							Chat.CPrivateChat.class, Chat.CPrivateChat.Builder.class);
		}

		public static final int SELF_FIELD_NUMBER = 1;

		private volatile Object self_;

		/**
		 * <pre>
		 *发送消息者的userid
		 * </pre>
		 *
		 * <code>string self = 1;</code>
		 */
		public String getSelf() {
			Object ref = self_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				self_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 *发送消息者的userid
		 * </pre>
		 *
		 * <code>string self = 1;</code>
		 */
		public com.google.protobuf.ByteString
		getSelfBytes() {
			Object ref = self_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				self_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DEST_FIELD_NUMBER = 2;

		private volatile Object dest_;

		/**
		 * <pre>
		 *消息目标的userid
		 * </pre>
		 *
		 * <code>string dest = 2;</code>
		 */
		public String getDest() {
			Object ref = dest_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				dest_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 *消息目标的userid
		 * </pre>
		 *
		 * <code>string dest = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getDestBytes() {
			Object ref = dest_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				dest_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int CONTENT_FIELD_NUMBER = 3;

		private volatile Object content_;

		/**
		 * <pre>
		 *消息内容
		 * </pre>
		 *
		 * <code>string content = 3;</code>
		 */
		public String getContent() {
			Object ref = content_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				content_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 *消息内容
		 * </pre>
		 *
		 * <code>string content = 3;</code>
		 */
		public com.google.protobuf.ByteString
		getContentBytes() {
			Object ref = content_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				content_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (!getSelfBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, self_);
			}
			if (!getDestBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dest_);
			}
			if (!getContentBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (!getSelfBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, self_);
			}
			if (!getDestBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dest_);
			}
			if (!getContentBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Chat.CPrivateChat)) {
				return super.equals(obj);
			}
			Chat.CPrivateChat other = (Chat.CPrivateChat) obj;

			boolean result = true;
			result = result && getSelf()
					.equals(other.getSelf());
			result = result && getDest()
					.equals(other.getDest());
			result = result && getContent()
					.equals(other.getContent());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + SELF_FIELD_NUMBER;
			hash = (53 * hash) + getSelf().hashCode();
			hash = (37 * hash) + DEST_FIELD_NUMBER;
			hash = (53 * hash) + getDest().hashCode();
			hash = (37 * hash) + CONTENT_FIELD_NUMBER;
			hash = (53 * hash) + getContent().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Chat.CPrivateChat parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Chat.CPrivateChat parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Chat.CPrivateChat parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Chat.CPrivateChat parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Chat.CPrivateChat parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Chat.CPrivateChat parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Chat.CPrivateChat parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Chat.CPrivateChat parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Chat.CPrivateChat parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static Chat.CPrivateChat parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Chat.CPrivateChat parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Chat.CPrivateChat parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Chat.CPrivateChat prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code CPrivateChat}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:CPrivateChat)
				Chat.CPrivateChatOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return Chat.internal_static_CPrivateChat_descriptor;
			}

			@Override
			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return Chat.internal_static_CPrivateChat_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Chat.CPrivateChat.class, Chat.CPrivateChat.Builder.class);
			}

			// Construct using com.wbq.protobuf.proto.Chat.CPrivateChat.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				self_ = "";

				dest_ = "";

				content_ = "";

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return Chat.internal_static_CPrivateChat_descriptor;
			}

			@Override
			public Chat.CPrivateChat getDefaultInstanceForType() {
				return Chat.CPrivateChat.getDefaultInstance();
			}

			@Override
			public Chat.CPrivateChat build() {
				Chat.CPrivateChat result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public Chat.CPrivateChat buildPartial() {
				Chat.CPrivateChat result = new Chat.CPrivateChat(this);
				result.self_ = self_;
				result.dest_ = dest_;
				result.content_ = content_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Chat.CPrivateChat) {
					return mergeFrom((Chat.CPrivateChat) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Chat.CPrivateChat other) {
				if (other == Chat.CPrivateChat.getDefaultInstance()) return this;
				if (!other.getSelf().isEmpty()) {
					self_ = other.self_;
					onChanged();
				}
				if (!other.getDest().isEmpty()) {
					dest_ = other.dest_;
					onChanged();
				}
				if (!other.getContent().isEmpty()) {
					content_ = other.content_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Chat.CPrivateChat parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Chat.CPrivateChat) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private Object self_ = "";

			/**
			 * <pre>
			 *发送消息者的userid
			 * </pre>
			 *
			 * <code>string self = 1;</code>
			 */
			public String getSelf() {
				Object ref = self_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					self_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 *发送消息者的userid
			 * </pre>
			 *
			 * <code>string self = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getSelfBytes() {
				Object ref = self_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					self_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 *发送消息者的userid
			 * </pre>
			 *
			 * <code>string self = 1;</code>
			 */
			public Builder setSelf(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				self_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *发送消息者的userid
			 * </pre>
			 *
			 * <code>string self = 1;</code>
			 */
			public Builder clearSelf() {

				self_ = getDefaultInstance().getSelf();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *发送消息者的userid
			 * </pre>
			 *
			 * <code>string self = 1;</code>
			 */
			public Builder setSelfBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				self_ = value;
				onChanged();
				return this;
			}

			private Object dest_ = "";

			/**
			 * <pre>
			 *消息目标的userid
			 * </pre>
			 *
			 * <code>string dest = 2;</code>
			 */
			public String getDest() {
				Object ref = dest_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					dest_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 *消息目标的userid
			 * </pre>
			 *
			 * <code>string dest = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getDestBytes() {
				Object ref = dest_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					dest_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 *消息目标的userid
			 * </pre>
			 *
			 * <code>string dest = 2;</code>
			 */
			public Builder setDest(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				dest_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *消息目标的userid
			 * </pre>
			 *
			 * <code>string dest = 2;</code>
			 */
			public Builder clearDest() {

				dest_ = getDefaultInstance().getDest();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *消息目标的userid
			 * </pre>
			 *
			 * <code>string dest = 2;</code>
			 */
			public Builder setDestBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				dest_ = value;
				onChanged();
				return this;
			}

			private Object content_ = "";

			/**
			 * <pre>
			 *消息内容
			 * </pre>
			 *
			 * <code>string content = 3;</code>
			 */
			public String getContent() {
				Object ref = content_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					content_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 *消息内容
			 * </pre>
			 *
			 * <code>string content = 3;</code>
			 */
			public com.google.protobuf.ByteString
			getContentBytes() {
				Object ref = content_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					content_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 *消息内容
			 * </pre>
			 *
			 * <code>string content = 3;</code>
			 */
			public Builder setContent(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				content_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *消息内容
			 * </pre>
			 *
			 * <code>string content = 3;</code>
			 */
			public Builder clearContent() {

				content_ = getDefaultInstance().getContent();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *消息内容
			 * </pre>
			 *
			 * <code>string content = 3;</code>
			 */
			public Builder setContentBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				content_ = value;
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:CPrivateChat)
		}

		// @@protoc_insertion_point(class_scope:CPrivateChat)
		private static final Chat.CPrivateChat DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Chat.CPrivateChat();
		}

		public static Chat.CPrivateChat getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<CPrivateChat>
				PARSER = new com.google.protobuf.AbstractParser<CPrivateChat>() {
			@Override
			public CPrivateChat parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CPrivateChat(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<CPrivateChat> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<CPrivateChat> getParserForType() {
			return PARSER;
		}

		@Override
		public Chat.CPrivateChat getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface SPrivateChatOrBuilder extends
			// @@protoc_insertion_point(interface_extends:SPrivateChat)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string content = 1;</code>
		 */
		String getContent();

		/**
		 * <code>string content = 1;</code>
		 */
		com.google.protobuf.ByteString
		getContentBytes();
	}

	/**
	 * Protobuf type {@code SPrivateChat}
	 */
	public static final class SPrivateChat extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:SPrivateChat)
			SPrivateChatOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use SPrivateChat.newBuilder() to construct.
		private SPrivateChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private SPrivateChat() {
			content_ = "";
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private SPrivateChat(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							String s = input.readStringRequireUtf8();

							content_ = s;
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return Chat.internal_static_SPrivateChat_descriptor;
		}

		@Override
		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return Chat.internal_static_SPrivateChat_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							Chat.SPrivateChat.class, Chat.SPrivateChat.Builder.class);
		}

		public static final int CONTENT_FIELD_NUMBER = 1;

		private volatile Object content_;

		/**
		 * <code>string content = 1;</code>
		 */
		public String getContent() {
			Object ref = content_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				content_ = s;
				return s;
			}
		}

		/**
		 * <code>string content = 1;</code>
		 */
		public com.google.protobuf.ByteString
		getContentBytes() {
			Object ref = content_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				content_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (!getContentBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (!getContentBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Chat.SPrivateChat)) {
				return super.equals(obj);
			}
			Chat.SPrivateChat other = (Chat.SPrivateChat) obj;

			boolean result = true;
			result = result && getContent()
					.equals(other.getContent());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + CONTENT_FIELD_NUMBER;
			hash = (53 * hash) + getContent().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Chat.SPrivateChat parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Chat.SPrivateChat parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Chat.SPrivateChat parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Chat.SPrivateChat parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Chat.SPrivateChat parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Chat.SPrivateChat parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Chat.SPrivateChat parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Chat.SPrivateChat parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Chat.SPrivateChat parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static Chat.SPrivateChat parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Chat.SPrivateChat parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Chat.SPrivateChat parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Chat.SPrivateChat prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code SPrivateChat}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:SPrivateChat)
				Chat.SPrivateChatOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return Chat.internal_static_SPrivateChat_descriptor;
			}

			@Override
			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return Chat.internal_static_SPrivateChat_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Chat.SPrivateChat.class, Chat.SPrivateChat.Builder.class);
			}

			// Construct using com.wbq.protobuf.proto.Chat.SPrivateChat.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				content_ = "";

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return Chat.internal_static_SPrivateChat_descriptor;
			}

			@Override
			public Chat.SPrivateChat getDefaultInstanceForType() {
				return Chat.SPrivateChat.getDefaultInstance();
			}

			@Override
			public Chat.SPrivateChat build() {
				Chat.SPrivateChat result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public Chat.SPrivateChat buildPartial() {
				Chat.SPrivateChat result = new Chat.SPrivateChat(this);
				result.content_ = content_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Chat.SPrivateChat) {
					return mergeFrom((Chat.SPrivateChat) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Chat.SPrivateChat other) {
				if (other == Chat.SPrivateChat.getDefaultInstance()) return this;
				if (!other.getContent().isEmpty()) {
					content_ = other.content_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Chat.SPrivateChat parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Chat.SPrivateChat) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private Object content_ = "";

			/**
			 * <code>string content = 1;</code>
			 */
			public String getContent() {
				Object ref = content_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					content_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <code>string content = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getContentBytes() {
				Object ref = content_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					content_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string content = 1;</code>
			 */
			public Builder setContent(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				content_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string content = 1;</code>
			 */
			public Builder clearContent() {

				content_ = getDefaultInstance().getContent();
				onChanged();
				return this;
			}

			/**
			 * <code>string content = 1;</code>
			 */
			public Builder setContentBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				content_ = value;
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:SPrivateChat)
		}

		// @@protoc_insertion_point(class_scope:SPrivateChat)
		private static final Chat.SPrivateChat DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Chat.SPrivateChat();
		}

		public static Chat.SPrivateChat getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<SPrivateChat>
				PARSER = new com.google.protobuf.AbstractParser<SPrivateChat>() {
			@Override
			public SPrivateChat parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new SPrivateChat(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<SPrivateChat> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<SPrivateChat> getParserForType() {
			return PARSER;
		}

		@Override
		public Chat.SPrivateChat getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_CPrivateChat_descriptor;

	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_CPrivateChat_fieldAccessorTable;

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_SPrivateChat_descriptor;

	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_SPrivateChat_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		String[] descriptorData = {
				"\n\nchat.proto\";\n\014CPrivateChat\022\014\n\004self\030\001 \001" +
						"(\t\022\014\n\004dest\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\"\037\n\014SPr" +
						"ivateChat\022\017\n\007content\030\001 \001(\tB\036\n\026com.wbq.pr" +
						"otobuf.protoB\004Chatb\006proto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {
						}, assigner);
		internal_static_CPrivateChat_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_CPrivateChat_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_CPrivateChat_descriptor,
				new String[] {"Self", "Dest", "Content",});
		internal_static_SPrivateChat_descriptor =
				getDescriptor().getMessageTypes().get(1);
		internal_static_SPrivateChat_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_SPrivateChat_descriptor,
				new String[] {"Content",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
