// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.wbq.protobuf.proto;

public final class Internal {
	private Internal() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	/**
	 * Protobuf enum {@code Dest}
	 */
	public enum Dest
			implements com.google.protobuf.ProtocolMessageEnum {
		/**
		 * <code>Client = 0;</code>
		 */
		Client(0),
		/**
		 * <code>Auth = 1;</code>
		 */
		Auth(1),
		/**
		 * <code>Logic = 2;</code>
		 */
		Logic(2),
		/**
		 * <code>Gate = 3;</code>
		 */
		Gate(3),
		UNRECOGNIZED(-1),
		;

		/**
		 * <code>Client = 0;</code>
		 */
		public static final int Client_VALUE = 0;

		/**
		 * <code>Auth = 1;</code>
		 */
		public static final int Auth_VALUE = 1;

		/**
		 * <code>Logic = 2;</code>
		 */
		public static final int Logic_VALUE = 2;

		/**
		 * <code>Gate = 3;</code>
		 */
		public static final int Gate_VALUE = 3;


		public final int getNumber() {
			if (this == UNRECOGNIZED) {
				throw new IllegalArgumentException(
						"Can't get the number of an unknown enum value.");
			}
			return value;
		}

		/**
		 * @deprecated Use {@link #forNumber(int)} instead.
		 */
		@Deprecated
		public static Dest valueOf(int value) {
			return forNumber(value);
		}

		public static Dest forNumber(int value) {
			switch (value) {
				case 0:
					return Client;
				case 1:
					return Auth;
				case 2:
					return Logic;
				case 3:
					return Gate;
				default:
					return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<Dest>
		internalGetValueMap() {
			return internalValueMap;
		}

		private static final com.google.protobuf.Internal.EnumLiteMap<
				Dest> internalValueMap =
				new com.google.protobuf.Internal.EnumLiteMap<Dest>() {
					public Dest findValueByNumber(int number) {
						return Dest.forNumber(number);
					}
				};

		public final com.google.protobuf.Descriptors.EnumValueDescriptor
		getValueDescriptor() {
			return getDescriptor().getValues().get(ordinal());
		}

		public final com.google.protobuf.Descriptors.EnumDescriptor
		getDescriptorForType() {
			return getDescriptor();
		}

		public static final com.google.protobuf.Descriptors.EnumDescriptor
		getDescriptor() {
			return Internal.getDescriptor().getEnumTypes().get(0);
		}

		private static final Dest[] VALUES = values();

		public static Dest valueOf(
				com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
			if (desc.getType() != getDescriptor()) {
				throw new IllegalArgumentException(
						"EnumValueDescriptor is not for this type.");
			}
			if (desc.getIndex() == -1) {
				return UNRECOGNIZED;
			}
			return VALUES[desc.getIndex()];
		}

		private final int value;

		private Dest(int value) {
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:Dest)
	}

	public interface GTransferOrBuilder extends
			// @@protoc_insertion_point(interface_extends:GTransfer)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>.Dest dest = 1;</code>
		 */
		int getDestValue();

		/**
		 * <code>.Dest dest = 1;</code>
		 */
		Internal.Dest getDest();

		/**
		 * <code>uint64 netId = 2;</code>
		 */
		long getNetId();

		/**
		 * <code>string userId = 3;</code>
		 */
		String getUserId();

		/**
		 * <code>string userId = 3;</code>
		 */
		com.google.protobuf.ByteString
		getUserIdBytes();

		/**
		 * <code>uint32 ptoNum = 4;</code>
		 */
		int getPtoNum();

		/**
		 * <code>bytes msg = 5;</code>
		 */
		com.google.protobuf.ByteString getMsg();
	}

	/**
	 * <pre>
	 *服务间的中转协议
	 * </pre>
	 *
	 * Protobuf type {@code GTransfer}
	 */
	public static final class GTransfer extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:GTransfer)
			GTransferOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use GTransfer.newBuilder() to construct.
		private GTransfer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private GTransfer() {
			dest_ = 0;
			netId_ = 0L;
			userId_ = "";
			ptoNum_ = 0;
			msg_ = com.google.protobuf.ByteString.EMPTY;
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private GTransfer(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {
							int rawValue = input.readEnum();

							dest_ = rawValue;
							break;
						}
						case 16: {

							netId_ = input.readUInt64();
							break;
						}
						case 26: {
							String s = input.readStringRequireUtf8();

							userId_ = s;
							break;
						}
						case 32: {

							ptoNum_ = input.readUInt32();
							break;
						}
						case 42: {

							msg_ = input.readBytes();
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return Internal.internal_static_GTransfer_descriptor;
		}

		@Override
		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return Internal.internal_static_GTransfer_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							Internal.GTransfer.class, Internal.GTransfer.Builder.class);
		}

		public static final int DEST_FIELD_NUMBER = 1;

		private int dest_;

		/**
		 * <code>.Dest dest = 1;</code>
		 */
		public int getDestValue() {
			return dest_;
		}

		/**
		 * <code>.Dest dest = 1;</code>
		 */
		public Internal.Dest getDest() {
			@SuppressWarnings("deprecation")
			Internal.Dest result = Internal.Dest.valueOf(dest_);
			return result == null ? Internal.Dest.UNRECOGNIZED : result;
		}

		public static final int NETID_FIELD_NUMBER = 2;

		private long netId_;

		/**
		 * <code>uint64 netId = 2;</code>
		 */
		public long getNetId() {
			return netId_;
		}

		public static final int USERID_FIELD_NUMBER = 3;

		private volatile Object userId_;

		/**
		 * <code>string userId = 3;</code>
		 */
		public String getUserId() {
			Object ref = userId_;
			if (ref instanceof String) {
				return (String) ref;
			}
			else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				userId_ = s;
				return s;
			}
		}

		/**
		 * <code>string userId = 3;</code>
		 */
		public com.google.protobuf.ByteString
		getUserIdBytes() {
			Object ref = userId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				userId_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PTONUM_FIELD_NUMBER = 4;

		private int ptoNum_;

		/**
		 * <code>uint32 ptoNum = 4;</code>
		 */
		public int getPtoNum() {
			return ptoNum_;
		}

		public static final int MSG_FIELD_NUMBER = 5;

		private com.google.protobuf.ByteString msg_;

		/**
		 * <code>bytes msg = 5;</code>
		 */
		public com.google.protobuf.ByteString getMsg() {
			return msg_;
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (dest_ != Internal.Dest.Client.getNumber()) {
				output.writeEnum(1, dest_);
			}
			if (netId_ != 0L) {
				output.writeUInt64(2, netId_);
			}
			if (!getUserIdBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userId_);
			}
			if (ptoNum_ != 0) {
				output.writeUInt32(4, ptoNum_);
			}
			if (!msg_.isEmpty()) {
				output.writeBytes(5, msg_);
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (dest_ != Internal.Dest.Client.getNumber()) {
				size += com.google.protobuf.CodedOutputStream
						.computeEnumSize(1, dest_);
			}
			if (netId_ != 0L) {
				size += com.google.protobuf.CodedOutputStream
						.computeUInt64Size(2, netId_);
			}
			if (!getUserIdBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userId_);
			}
			if (ptoNum_ != 0) {
				size += com.google.protobuf.CodedOutputStream
						.computeUInt32Size(4, ptoNum_);
			}
			if (!msg_.isEmpty()) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(5, msg_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Internal.GTransfer)) {
				return super.equals(obj);
			}
			Internal.GTransfer other = (Internal.GTransfer) obj;

			boolean result = true;
			result = result && dest_ == other.dest_;
			result = result && (getNetId()
					== other.getNetId());
			result = result && getUserId()
					.equals(other.getUserId());
			result = result && (getPtoNum()
					== other.getPtoNum());
			result = result && getMsg()
					.equals(other.getMsg());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + DEST_FIELD_NUMBER;
			hash = (53 * hash) + dest_;
			hash = (37 * hash) + NETID_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
					getNetId());
			hash = (37 * hash) + USERID_FIELD_NUMBER;
			hash = (53 * hash) + getUserId().hashCode();
			hash = (37 * hash) + PTONUM_FIELD_NUMBER;
			hash = (53 * hash) + getPtoNum();
			hash = (37 * hash) + MSG_FIELD_NUMBER;
			hash = (53 * hash) + getMsg().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Internal.GTransfer parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Internal.GTransfer parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Internal.GTransfer parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Internal.GTransfer parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Internal.GTransfer parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Internal.GTransfer parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Internal.GTransfer parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Internal.GTransfer parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Internal.GTransfer parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static Internal.GTransfer parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Internal.GTransfer parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Internal.GTransfer parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Internal.GTransfer prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * <pre>
		 *服务间的中转协议
		 * </pre>
		 *
		 * Protobuf type {@code GTransfer}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:GTransfer)
				Internal.GTransferOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return Internal.internal_static_GTransfer_descriptor;
			}

			@Override
			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return Internal.internal_static_GTransfer_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Internal.GTransfer.class, Internal.GTransfer.Builder.class);
			}

			// Construct using com.wbq.protobuf.proto.Internal.GTransfer.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				dest_ = 0;

				netId_ = 0L;

				userId_ = "";

				ptoNum_ = 0;

				msg_ = com.google.protobuf.ByteString.EMPTY;

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return Internal.internal_static_GTransfer_descriptor;
			}

			@Override
			public Internal.GTransfer getDefaultInstanceForType() {
				return Internal.GTransfer.getDefaultInstance();
			}

			@Override
			public Internal.GTransfer build() {
				Internal.GTransfer result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public Internal.GTransfer buildPartial() {
				Internal.GTransfer result = new Internal.GTransfer(this);
				result.dest_ = dest_;
				result.netId_ = netId_;
				result.userId_ = userId_;
				result.ptoNum_ = ptoNum_;
				result.msg_ = msg_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Internal.GTransfer) {
					return mergeFrom((Internal.GTransfer) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Internal.GTransfer other) {
				if (other == Internal.GTransfer.getDefaultInstance()) return this;
				if (other.dest_ != 0) {
					setDestValue(other.getDestValue());
				}
				if (other.getNetId() != 0L) {
					setNetId(other.getNetId());
				}
				if (!other.getUserId().isEmpty()) {
					userId_ = other.userId_;
					onChanged();
				}
				if (other.getPtoNum() != 0) {
					setPtoNum(other.getPtoNum());
				}
				if (other.getMsg() != com.google.protobuf.ByteString.EMPTY) {
					setMsg(other.getMsg());
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Internal.GTransfer parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Internal.GTransfer) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int dest_ = 0;

			/**
			 * <code>.Dest dest = 1;</code>
			 */
			public int getDestValue() {
				return dest_;
			}

			/**
			 * <code>.Dest dest = 1;</code>
			 */
			public Builder setDestValue(int value) {
				dest_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>.Dest dest = 1;</code>
			 */
			public Internal.Dest getDest() {
				@SuppressWarnings("deprecation")
				Internal.Dest result = Internal.Dest.valueOf(dest_);
				return result == null ? Internal.Dest.UNRECOGNIZED : result;
			}

			/**
			 * <code>.Dest dest = 1;</code>
			 */
			public Builder setDest(Internal.Dest value) {
				if (value == null) {
					throw new NullPointerException();
				}

				dest_ = value.getNumber();
				onChanged();
				return this;
			}

			/**
			 * <code>.Dest dest = 1;</code>
			 */
			public Builder clearDest() {

				dest_ = 0;
				onChanged();
				return this;
			}

			private long netId_;

			/**
			 * <code>uint64 netId = 2;</code>
			 */
			public long getNetId() {
				return netId_;
			}

			/**
			 * <code>uint64 netId = 2;</code>
			 */
			public Builder setNetId(long value) {

				netId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>uint64 netId = 2;</code>
			 */
			public Builder clearNetId() {

				netId_ = 0L;
				onChanged();
				return this;
			}

			private Object userId_ = "";

			/**
			 * <code>string userId = 3;</code>
			 */
			public String getUserId() {
				Object ref = userId_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					userId_ = s;
					return s;
				}
				else {
					return (String) ref;
				}
			}

			/**
			 * <code>string userId = 3;</code>
			 */
			public com.google.protobuf.ByteString
			getUserIdBytes() {
				Object ref = userId_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					userId_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string userId = 3;</code>
			 */
			public Builder setUserId(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				userId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string userId = 3;</code>
			 */
			public Builder clearUserId() {

				userId_ = getDefaultInstance().getUserId();
				onChanged();
				return this;
			}

			/**
			 * <code>string userId = 3;</code>
			 */
			public Builder setUserIdBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				userId_ = value;
				onChanged();
				return this;
			}

			private int ptoNum_;

			/**
			 * <code>uint32 ptoNum = 4;</code>
			 */
			public int getPtoNum() {
				return ptoNum_;
			}

			/**
			 * <code>uint32 ptoNum = 4;</code>
			 */
			public Builder setPtoNum(int value) {

				ptoNum_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>uint32 ptoNum = 4;</code>
			 */
			public Builder clearPtoNum() {

				ptoNum_ = 0;
				onChanged();
				return this;
			}

			private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;

			/**
			 * <code>bytes msg = 5;</code>
			 */
			public com.google.protobuf.ByteString getMsg() {
				return msg_;
			}

			/**
			 * <code>bytes msg = 5;</code>
			 */
			public Builder setMsg(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}

				msg_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>bytes msg = 5;</code>
			 */
			public Builder clearMsg() {

				msg_ = getDefaultInstance().getMsg();
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:GTransfer)
		}

		// @@protoc_insertion_point(class_scope:GTransfer)
		private static final Internal.GTransfer DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Internal.GTransfer();
		}

		public static Internal.GTransfer getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<GTransfer>
				PARSER = new com.google.protobuf.AbstractParser<GTransfer>() {
			@Override
			public GTransfer parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new GTransfer(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<GTransfer> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<GTransfer> getParserForType() {
			return PARSER;
		}

		@Override
		public Internal.GTransfer getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface GreetOrBuilder extends
			// @@protoc_insertion_point(interface_extends:Greet)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>.Greet.From from = 1;</code>
		 */
		int getFromValue();

		/**
		 * <code>.Greet.From from = 1;</code>
		 */
		Internal.Greet.From getFrom();
	}

	/**
	 * <pre>
	 *服务间建立连接时发送的协议
	 * </pre>
	 *
	 * Protobuf type {@code Greet}
	 */
	public static final class Greet extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:Greet)
			GreetOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use Greet.newBuilder() to construct.
		private Greet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Greet() {
			from_ = 0;
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private Greet(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {
							int rawValue = input.readEnum();

							from_ = rawValue;
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return Internal.internal_static_Greet_descriptor;
		}

		@Override
		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return Internal.internal_static_Greet_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							Internal.Greet.class, Internal.Greet.Builder.class);
		}

		/**
		 * Protobuf enum {@code Greet.From}
		 */
		public enum From
				implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>Logic = 0;</code>
			 */
			Logic(0),
			/**
			 * <code>Gate = 1;</code>
			 */
			Gate(1),
			/**
			 * <code>Auth = 2;</code>
			 */
			Auth(2),
			UNRECOGNIZED(-1),
			;

			/**
			 * <code>Logic = 0;</code>
			 */
			public static final int Logic_VALUE = 0;

			/**
			 * <code>Gate = 1;</code>
			 */
			public static final int Gate_VALUE = 1;

			/**
			 * <code>Auth = 2;</code>
			 */
			public static final int Auth_VALUE = 2;


			public final int getNumber() {
				if (this == UNRECOGNIZED) {
					throw new IllegalArgumentException(
							"Can't get the number of an unknown enum value.");
				}
				return value;
			}

			/**
			 * @deprecated Use {@link #forNumber(int)} instead.
			 */
			@Deprecated
			public static From valueOf(int value) {
				return forNumber(value);
			}

			public static From forNumber(int value) {
				switch (value) {
					case 0:
						return Logic;
					case 1:
						return Gate;
					case 2:
						return Auth;
					default:
						return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<From>
			internalGetValueMap() {
				return internalValueMap;
			}

			private static final com.google.protobuf.Internal.EnumLiteMap<
					From> internalValueMap =
					new com.google.protobuf.Internal.EnumLiteMap<From>() {
						public From findValueByNumber(int number) {
							return From.forNumber(number);
						}
					};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor
			getValueDescriptor() {
				return getDescriptor().getValues().get(ordinal());
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptor() {
				return Internal.Greet.getDescriptor().getEnumTypes().get(0);
			}

			private static final From[] VALUES = values();

			public static From valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				if (desc.getIndex() == -1) {
					return UNRECOGNIZED;
				}
				return VALUES[desc.getIndex()];
			}

			private final int value;

			private From(int value) {
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:Greet.From)
		}

		public static final int FROM_FIELD_NUMBER = 1;

		private int from_;

		/**
		 * <code>.Greet.From from = 1;</code>
		 */
		public int getFromValue() {
			return from_;
		}

		/**
		 * <code>.Greet.From from = 1;</code>
		 */
		public Internal.Greet.From getFrom() {
			@SuppressWarnings("deprecation")
			Internal.Greet.From result = Internal.Greet.From.valueOf(from_);
			return result == null ? Internal.Greet.From.UNRECOGNIZED : result;
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (from_ != Internal.Greet.From.Logic.getNumber()) {
				output.writeEnum(1, from_);
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (from_ != Internal.Greet.From.Logic.getNumber()) {
				size += com.google.protobuf.CodedOutputStream
						.computeEnumSize(1, from_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Internal.Greet)) {
				return super.equals(obj);
			}
			Internal.Greet other = (Internal.Greet) obj;

			boolean result = true;
			result = result && from_ == other.from_;
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + FROM_FIELD_NUMBER;
			hash = (53 * hash) + from_;
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Internal.Greet parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Internal.Greet parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Internal.Greet parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Internal.Greet parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Internal.Greet parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Internal.Greet parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Internal.Greet parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Internal.Greet parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Internal.Greet parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static Internal.Greet parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Internal.Greet parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Internal.Greet parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Internal.Greet prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * <pre>
		 *服务间建立连接时发送的协议
		 * </pre>
		 *
		 * Protobuf type {@code Greet}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:Greet)
				Internal.GreetOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return Internal.internal_static_Greet_descriptor;
			}

			@Override
			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return Internal.internal_static_Greet_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Internal.Greet.class, Internal.Greet.Builder.class);
			}

			// Construct using com.wbq.protobuf.proto.Internal.Greet.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				from_ = 0;

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return Internal.internal_static_Greet_descriptor;
			}

			@Override
			public Internal.Greet getDefaultInstanceForType() {
				return Internal.Greet.getDefaultInstance();
			}

			@Override
			public Internal.Greet build() {
				Internal.Greet result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public Internal.Greet buildPartial() {
				Internal.Greet result = new Internal.Greet(this);
				result.from_ = from_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Internal.Greet) {
					return mergeFrom((Internal.Greet) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Internal.Greet other) {
				if (other == Internal.Greet.getDefaultInstance()) return this;
				if (other.from_ != 0) {
					setFromValue(other.getFromValue());
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Internal.Greet parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Internal.Greet) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int from_ = 0;

			/**
			 * <code>.Greet.From from = 1;</code>
			 */
			public int getFromValue() {
				return from_;
			}

			/**
			 * <code>.Greet.From from = 1;</code>
			 */
			public Builder setFromValue(int value) {
				from_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>.Greet.From from = 1;</code>
			 */
			public Internal.Greet.From getFrom() {
				@SuppressWarnings("deprecation")
				Internal.Greet.From result = Internal.Greet.From.valueOf(from_);
				return result == null ? Internal.Greet.From.UNRECOGNIZED : result;
			}

			/**
			 * <code>.Greet.From from = 1;</code>
			 */
			public Builder setFrom(Internal.Greet.From value) {
				if (value == null) {
					throw new NullPointerException();
				}

				from_ = value.getNumber();
				onChanged();
				return this;
			}

			/**
			 * <code>.Greet.From from = 1;</code>
			 */
			public Builder clearFrom() {

				from_ = 0;
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:Greet)
		}

		// @@protoc_insertion_point(class_scope:Greet)
		private static final Internal.Greet DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Internal.Greet();
		}

		public static Internal.Greet getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Greet>
				PARSER = new com.google.protobuf.AbstractParser<Greet>() {
			@Override
			public Greet parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Greet(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Greet> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<Greet> getParserForType() {
			return PARSER;
		}

		@Override
		public Internal.Greet getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_GTransfer_descriptor;

	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_GTransfer_fieldAccessorTable;

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_Greet_descriptor;

	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_Greet_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		String[] descriptorData = {
				"\n\016internal.proto\"\\\n\tGTransfer\022\023\n\004dest\030\001 " +
						"\001(\0162\005.Dest\022\r\n\005netId\030\002 \001(\004\022\016\n\006userId\030\003 \001(" +
						"\t\022\016\n\006ptoNum\030\004 \001(\r\022\013\n\003msg\030\005 \001(\014\"I\n\005Greet\022" +
						"\031\n\004from\030\001 \001(\0162\013.Greet.From\"%\n\004From\022\t\n\005Lo" +
						"gic\020\000\022\010\n\004Gate\020\001\022\010\n\004Auth\020\002*1\n\004Dest\022\n\n\006Cli" +
						"ent\020\000\022\010\n\004Auth\020\001\022\t\n\005Logic\020\002\022\010\n\004Gate\020\003B\"\n\026" +
						"com.wbq.protobuf.protoB\010Internalb\006proto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {
						}, assigner);
		internal_static_GTransfer_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_GTransfer_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_GTransfer_descriptor,
				new String[] {"Dest", "NetId", "UserId", "PtoNum", "Msg",});
		internal_static_Greet_descriptor =
				getDescriptor().getMessageTypes().get(1);
		internal_static_Greet_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_Greet_descriptor,
				new String[] {"From",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
